export const GET_LOCATION_START = "GET_LOCATION_START";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_LOCATION_FAILURE = "GET_LOCATION_FAILURE";

export const GET_ADDRESS_START = "GET_ADDRESS_START";
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS";
export const GET_ADDRESS_FAILURE = "GET_ADDRESS_FAILURE";

export const GET_WEATHER_STATUS_START = "GET_WEATHER_STATUS_START";
export const GET_WEATHER_STATUS_SUCCESS = "GET_WEATHER_STATUS_SUCCESS";
export const GET_WEATHER_STATUS_FAILURE = "GET_WEATHER_STATUS_FAILURE";